import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // supabase/.temp holds the CLI's vendored edge-runtime sources, which are not
  // ours to lint or format; coverage/ and .nitro are build output.
  { ignores: ["dist", ".output", ".vinxi", ".nitro", "coverage", "supabase/.temp"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // src/components/ui/ is vendored shadcn code, regenerated by its CLI rather than
  // maintained here. Six of those files export a style-variant function or a hook
  // alongside their component (buttonVariants, useSidebar, and so on), which costs a
  // full page reload instead of a hot swap when the file is edited in dev — a price
  // never paid, because these files are not edited by hand.
  //
  // Splitting the exports would fix it properly, but the CLI would undo it on the next
  // regeneration. Warnings nobody intends to act on are worse than none: they train you
  // to skim past lint output, which is where a real one eventually hides. So the rule is
  // off for this directory only, and stays on everywhere else.
  {
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  eslintPluginPrettier,
);
