#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# GitHub probe tokens for #20 / #74.
#
# Creates two THROWAWAY fine-grained, read-only tokens (one per GitHub account),
# runs scripts/github/github_probe.py with them, then helps you revoke them. The
# production tokens are made later, for #77, with the same permission choices but a
# 90-day expiry, and are pasted straight into Railway, never through this wizard.
#
# Nothing here is a CI secret, so no set_secret call: the tokens live only in the
# gitignored .env.local and are blanked again in the last stage.

TOTAL_STAGES=5

# Work from the repo root (this file lives in scripts/github/), and keep the tokens
# in .env.local, which is gitignored, rather than the template's default .env.
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".env.local"

NEW_TOKEN_URL="https://github.com/settings/personal-access-tokens/new"
TOKEN_LIST_URL="https://github.com/settings/personal-access-tokens"
PROBE_REPORT="${TMPDIR:-/tmp}/github-probe-report.txt"

# find_python prints the first interpreter that is really Python 3.9+. The Windows
# Store "python3" stub fails the version check, so it is skipped.
find_python() {
  local candidate
  for candidate in python3 python py; do
    if command -v "$candidate" >/dev/null 2>&1 \
      && "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' >/dev/null 2>&1; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  return 1
}

# require_fine_grained NAME VALUE refuses anything that is not a fine-grained token.
# Classic tokens (ghp_...) are ruled out by #20 because they cannot be read-only.
require_fine_grained() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "Nothing was entered for $name. Re-run the wizard."
    exit 1
  fi
  case "$value" in
    github_pat_*) ;;
    ghp_* | gho_* | ghu_* | ghs_*)
      warn "$name is a classic or OAuth token. #20 rules those out. Make a fine-grained one."
      exit 1
      ;;
    *)
      warn "$name does not look like a fine-grained token (they start with github_pat_)."
      exit 1
      ;;
  esac
}

# run_probe runs the probe and keeps a copy of its (counts-only) report.
run_probe() {
  local python
  if ! python=$(find_python); then
    warn "Python 3.9 or newer was not found. Install it, then re-run the wizard."
    exit 1
  fi
  if ! "$python" scripts/github/github_probe.py --env-file "$ENV_FILE" \
    --b-private-setting "$B_PRIVATE_SETTING" | tee "$PROBE_REPORT"; then
    warn "The probe reported a problem (see above). The tokens are still saved."
  fi
}

banner "GitHub probe tokens (#20 / #74)"

# ── 1. Two-factor and identities ──────────────────────────────────────────
stage "Before any token exists: two-factor and who is who"
say "A token is only as safe as the account behind it, so check this first."
open_url "https://github.com/settings/security"
step "Signed in as account A: two-factor authentication should say Enabled."
confirm "Is two-factor on for account A?" || SKIPPED+=("Turn on two-factor for GitHub account A")
step "Now account B (a private window helps): same page, same check."
confirm "Is two-factor on for account B?" || SKIPPED+=("Turn on two-factor for GitHub account B")
step "Railway: your account settings, security section. Not needed for the probe, but #77 needs it."
confirm "Is two-factor on for Railway?" || SKIPPED+=("Turn on two-factor for Railway before #77")
printf '\n'
say "The probe refuses a token that belongs to a different account than you expect."
ask GITHUB_LOGIN_A "Account A's GitHub username:"
ask GITHUB_LOGIN_B "Account B's GitHub username:"
write_env GITHUB_LOGIN_A "$GITHUB_LOGIN_A"
write_env GITHUB_LOGIN_B "$GITHUB_LOGIN_B"
printf '\n'
say "Account B's profile has a Contributions settings dropdown above the graph, with a"
say "'Private contributions' tick-box. Check it now; the report records it (check 4)."
ask B_PRIVATE_SETTING "Is B's 'Private contributions' ticked? (on / off / unknown):"
case "$B_PRIVATE_SETTING" in on | off | unknown) ;; *) B_PRIVATE_SETTING="unknown" ;; esac

# ── 2. Account A token ────────────────────────────────────────────────────
stage "Account A: create a throwaway read-only token"
say "Sign in to GitHub as account A first (check the avatar menu shows its username)."
open_url "$NEW_TOKEN_URL"
step "Token name: po-probe-A"
step "Expiration: Custom, about a week from today (this token is throwaway)."
step "Resource owner: account A itself, not an organisation."
step "Repository access: Only select repositories, then pick the repos A owns that you commit to."
note "     (the probe's 'unsplit' line tells us if you missed one)"
step "Permissions: leave EVERY permission at No access. Metadata: Read-only is added"
say "      automatically and cannot be removed. Add nothing under Account permissions."
step "Click Generate token, then copy it. GitHub shows it exactly once."
ask_secret GITHUB_TOKEN_A "Paste account A's token (hidden):"
require_fine_grained GITHUB_TOKEN_A "$GITHUB_TOKEN_A"
write_env GITHUB_TOKEN_A "$GITHUB_TOKEN_A"

# ── 3. Account B token ────────────────────────────────────────────────────
stage "Account B: create a throwaway read-only token"
say "Switch to account B: sign out, or open a private window signed in as B."
say "Check the avatar menu shows B's username before you continue."
open_url "$NEW_TOKEN_URL"
step "Token name: po-probe-B"
step "Expiration: Custom, about a week from today."
step "Resource owner: account B itself, not an organisation."
step "Repository access: Only select repositories, then pick B's two repos and nothing else."
step "Permissions: leave EVERY permission at No access (Metadata: Read-only is automatic)."
step "Click Generate token, then copy it."
warn "This wizard never asks for, or prints, a repository name. Only the token."
ask_secret GITHUB_TOKEN_B "Paste account B's token (hidden):"
require_fine_grained GITHUB_TOKEN_B "$GITHUB_TOKEN_B"
write_env GITHUB_TOKEN_B "$GITHUB_TOKEN_B"

# ── 4. Probe ──────────────────────────────────────────────────────────────
stage "Run the probe"
say "It reads totals and timestamps only. It never selects a repo name, message or URL,"
say "and account B's token is never asked about repositories at all."
printf '\n'
run_probe
printf '\n'
while confirm "Run it again (for example after changing B's Private contributions setting)?"; do
  ask B_PRIVATE_SETTING "Is B's 'Private contributions' ticked now? (on / off / unknown):"
  case "$B_PRIVATE_SETTING" in on | off | unknown) ;; *) B_PRIVATE_SETTING="unknown" ;; esac
  printf '\n'
  run_probe
  printf '\n'
done

# ── 5. Hand back and revoke ───────────────────────────────────────────────
stage "Hand the report back, then revoke the tokens"
say "The report is saved at: $PROBE_REPORT"
say "It holds counts, booleans and timestamps only, so it is safe to paste to Claude."
say "Paste it into the session so the findings go into the note and #74 can be ticked."
printf '\n'
warn "If the report says Metadata-only is NOT enough (typed totals all zero, or unsplit"
warn "above zero for B), do not revoke yet: re-run this wizard with Contents: Read-only added."
printf '\n'
if confirm "Report handed back and findings recorded? Revoke the throwaway tokens now?"; then
  open_url "$TOKEN_LIST_URL"
  step "As account A: open po-probe-A and click Delete (or Revoke)."
  step "As account B (private window): open po-probe-B and click Delete (or Revoke)."
  pause "Press Enter once both are deleted."
  write_env GITHUB_TOKEN_A ""
  write_env GITHUB_TOKEN_B ""
else
  SKIPPED+=("Revoke po-probe-A and po-probe-B at $TOKEN_LIST_URL once the findings are recorded")
  SKIPPED+=("Blank GITHUB_TOKEN_A and GITHUB_TOKEN_B in $ENV_FILE when you do")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
