#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# GitHub probe token for account B (#20 / #74).
#
# Account A is settled: fine-grained, read-only, and its probe results are in
# docs/integrations/GITHUB_MULTI_ACCOUNT.md. This wizard is for B only.
#
# B's private work comes back from GitHub as one anonymous lump unless the token is a
# CLASSIC token carrying the read:user scope (fine-grained tokens have no equivalent).
# So this makes one THROWAWAY classic token with read:user and nothing else, runs
# scripts/github/github_probe.py with --audit-exposure to learn what that token can and
# cannot read (including whether any name is readable), then helps you delete it.
#
# Nothing here is a CI secret, so no set_secret call: the token lives only in the
# gitignored .env.local and is blanked again in the last stage.

TOTAL_STAGES=4

# Work from the repo root (this file lives in scripts/github/), and keep the token
# in .env.local, which is gitignored, rather than the template's default .env.
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".env.local"

# GitHub prefills a classic token's name, scopes and expiry from these query parameters.
NEW_TOKEN_URL="https://github.com/settings/tokens/new?scopes=read:user&description=po-probe-B&default_expires_at=7"
TOKEN_LIST_URL="https://github.com/settings/tokens"
PROBE_REPORT="${TMPDIR:-/tmp}/github-probe-report.txt"

# find_python prints the first interpreter that is really Python 3.9+. The Windows
# Store "python3" stub fails the version check, so it is skipped.
find_python() {
  local candidate
  for candidate in python3 python py; do
    if command -v "$candidate" >/dev/null 2>&1 \
      && "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' >/dev/null 2>&1; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  return 1
}

# require_classic NAME VALUE refuses anything that is not a classic token (ghp_...).
# A fine-grained token cannot carry read:user, so it would just reproduce the lump.
require_classic() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "Nothing was entered for $name. Re-run the wizard."
    exit 1
  fi
  case "$value" in
    ghp_*) ;;
    github_pat_*)
      warn "$name is a fine-grained token. It cannot carry read:user, which is the whole point."
      warn "Use the classic page: $TOKEN_LIST_URL → Generate new token (classic)."
      exit 1
      ;;
    *)
      warn "$name does not look like a classic token (they start with ghp_)."
      exit 1
      ;;
  esac
}

# run_probe runs the probe with the exposure audit and keeps a copy of its report.
# The report holds counts, booleans and timestamps only.
run_probe() {
  local python
  if ! python=$(find_python); then
    warn "Python 3.9 or newer was not found. Install it, then re-run the wizard."
    exit 1
  fi
  if ! "$python" scripts/github/github_probe.py --env-file "$ENV_FILE" \
    --b-private-setting "$B_PRIVATE_SETTING" --audit-exposure | tee "$PROBE_REPORT"; then
    warn "The probe reported a problem (see above). The token is still saved."
  fi
}

banner "GitHub probe token for account B (#20 / #74)"

# ── 1. Two-factor and identity ────────────────────────────────────────────
stage "Before the token exists: two-factor and who is who"
say "A token is only as safe as the account behind it, so check this first."
open_url "https://github.com/settings/security"
step "Signed in as account B (a private window helps): two-factor should say Enabled."
confirm "Is two-factor on for account B?" || SKIPPED+=("Turn on two-factor for GitHub account B")
printf '\n'
say "The probe refuses a token that belongs to a different account than you expect."
ask GITHUB_LOGIN_B "Account B's GitHub username:"
write_env GITHUB_LOGIN_B "$GITHUB_LOGIN_B"
# The first probe run showed an unsplit count above zero, which GitHub only reports
# when B's 'Private contributions' profile setting is on.
B_PRIVATE_SETTING="on"
# Account A is not part of this run. Make sure a leftover token cannot be picked up.
write_env GITHUB_TOKEN_A ""

# ── 2. Account B classic token ────────────────────────────────────────────
stage "Account B: create a throwaway classic token with read:user only"
say "Stay signed in as account B (check the avatar menu shows its username)."
say "This is a CLASSIC token, deliberately. read:user is the one scope that lets GitHub"
say "split private work by type, and fine-grained tokens cannot carry it."
open_url "$NEW_TOKEN_URL"
step "Note: po-probe-B  (the page should arrive pre-filled)"
step "Expiration: 7 days (this token is throwaway)."
step "Scopes: tick read:user and NOTHING else. Under 'user' it is the first box."
warn "Do not tick 'repo', 'user' itself, 'user:email' or anything else."
say "      The probe reads the token's scopes back and flags anything extra."
step "Click Generate token, then copy it. GitHub shows it exactly once."
ask_secret GITHUB_TOKEN_B "Paste account B's token (hidden):"
require_classic GITHUB_TOKEN_B "$GITHUB_TOKEN_B"
write_env GITHUB_TOKEN_B "$GITHUB_TOKEN_B"

# ── 3. Probe ──────────────────────────────────────────────────────────────
stage "Run the probe and the exposure audit"
say "It reads totals, the token's scopes, and asks what names the token can read."
say "Names themselves are never printed or saved: only yes/no and counts."
printf '\n'
run_probe
printf '\n'
while confirm "Run it again?"; do
  printf '\n'
  run_probe
  printf '\n'
done

# ── 4. Hand back and revoke ───────────────────────────────────────────────
stage "Hand the report back, then delete the token"
say "The report is saved at: $PROBE_REPORT"
say "It holds counts, booleans and timestamps only, so it is safe to paste to Claude."
say "Paste it into the session so the findings go into the note and #74 can be ticked."
printf '\n'
if confirm "Report handed back? Delete the throwaway token now?"; then
  open_url "$TOKEN_LIST_URL"
  step "As account B: find po-probe-B and click Delete."
  pause "Press Enter once it is deleted."
  write_env GITHUB_TOKEN_B ""
else
  SKIPPED+=("Delete po-probe-B at $TOKEN_LIST_URL once the findings are recorded")
  SKIPPED+=("Blank GITHUB_TOKEN_B in $ENV_FILE when you do")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
